routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ApropsController;
use App\Http\Controllers\TagController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::resource('products', ProductController::class);

Route::resource('cat', TagController::class);

// Route::get('/', [App\Http\Controllers\ProductController::class, 'shows'])->name('home');

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('aprop', ApropsController::class);

Route::get('cart', [ProductController::class, 'cart'])->name('cart');
Route::get('add-to-cart/{id}', [ProductController::class, 'addToCart'])->name('add.to.cart');
// Route::patch('update-cart', [ProductController::class, 'update'])->name('update.cart');
// Route::delete('remove-from-cart', [ProductController::class, 'remove'])->name('remove.from.cart');

resources/views/cart.blade.php
@extends('layouts.app')



@section('content')
<table id="cart" class="table table-hover table-condensed">
    <thead>
        <tr>
            <th style="width:50%">Product</th>
            <th style="width:10%">Price</th>
            <th style="width:8%">Quantity</th>
            <th style="width:22%" class="text-center">Subtotal</th>
            <th style="width:10%"></th>
        </tr>
    </thead>
    <tbody>
        @php $total = 0 @endphp
        @if(session('cart'))
            @foreach(session('cart') as $id => $product)
                @php $total += $product['price'] * $product['quantity'] @endphp
                <tr data-id="{{ $id }}">
                    <td data-th="Product">
                        <div class="row">
                            <div class="col-sm-3 hidden-xs"><img src="#" width="100" height="100" class="img-responsive"/></div>
                            <div class="col-sm-9">
                                <h4 class="nomargin">{{ $product->name }}</h4>
                            </div>
                        </div>
                    </td>
                    <td data-th="Price">${{ $product['price'] }}</td>
                    <td data-th="Quantity">
                        <input type="number" value="{{ $details['quantity'] }}" class="form-control quantity update-cart" />
                    </td>
                    <td data-th="Subtotal" class="text-center">${{ $product['price'] * $product['quantity'] }}</td>
                    <td class="actions" data-th="">
                        <button class="btn btn-danger btn-sm remove-from-cart"><i class="fa fa-trash-o"></i></button>
                    </td>
                </tr>
            @endforeach
        @endif
    </tbody>
    <tfoot>
        <tr>
            <td colspan="5" class="text-right"><h3><strong>Total ${{ $total }}</strong></h3></td>
        </tr>
        <tr>
            <td colspan="5" class="text-right">
                <a href="{{ url('/') }}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a>
                <button class="btn btn-success">Checkout</button>
            </td>
        </tr>
    </tfoot>
</table>
@endsection

resources/views/home.blade.php
@extends('layouts')
<style>
	@import url('https://fonts.googleapis.com/css2?family=Fira+Sans+Extra+Condensed:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
	@import url('https://fonts.googleapis.com/css2?family=Heebo:wght@100;200;300;400;500;600;700;800;900&display=swap');
	@import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
	@import url("https://use.fontawesome.com/releases/v5.13.0/css/all.css");
	body{
		background: linear-gradient(90deg, #e8e8e8 50%, #3d009e 50%);
	}


	.card {
		background: #fff;
		box-shadow: 0 6px 10px rgba(0, 0, 0, .08), 0 0 6px rgba(0, 0, 0, .05);
		transition: .3s transform cubic-bezier(.155, 1.105, .295, 1.12), .3s box-shadow, .3s -webkit-transform cubic-bezier(.155, 1.105, .295, 1.12);
		border: 0;
		border-radius: 1rem;
	}

	.card-img,
	.card-img-top {
		border-top-left-radius: calc(1rem - 1px);
		border-top-right-radius: calc(1rem - 1px);
	}


	.card h5 {
		overflow: hidden;
		height: 55px;
		font-weight: 300;
		font-size: 1rem;
	}

	.card h5 a {
		color: black;
		text-decoration: none;
	}

	.card-img-top {
		width: 100%;
		min-height: 250px;
		max-height: 250px;
		object-fit: contain;
		padding: 30px;
	}

	.card h2 {
		font-size: 1rem;
	}


	.card:hover {
		transform: scale(1.02);
		box-shadow: 0 10px 20px rgba(0, 0, 0, .12), 0 4px 8px rgba(0, 0, 0, .06);
	}

	/* Centered text */
	.label-top {
		position: absolute;
		background-color: var(--label-index);
		color: #fff;
		top: 8px;
		right: 8px;
		padding: 5px 10px 5px 10px;
		font-size: .7rem;
		font-weight: 600;
		border-radius: 3px;
		text-transform: uppercase;
	}

	.top-right {
		position: absolute;
		top: 24px;
		left: 24px;

		width: 90px;
		height: 90px;
		border-radius: 50%;
		font-size: 1rem;
		font-weight: 900;
		background: #8bc34a;
		line-height: 90px;
		text-align: center;
		color: white;
	}

	.top-right span {
		display: inline-block;
		vertical-align: middle;
		/* line-height: normal; */
		/* padding: 0 25px; */
	}

	.aff-link {
		/* text-decoration: overline; */
		font-weight: 500;
	}

	.over-bg {
		background: rgba(53, 53, 53, 0.85);
		box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
		backdrop-filter: blur(0.0px);
		-webkit-backdrop-filter: blur(0.0px);
		border-radius: 10px;
	}

	.bold-btn {

		font-size: 1rem;
		font-weight: 500;
		text-transform: uppercase;
		padding: 5px 50px 5px 50px;
	}

	.box .btn {
		font-size: 1.5rem;
	}

	@media (max-width: 1025px) {
		.btn {
			padding: 5px 40px 5px 40px;
		}
	}

	@media (max-width: 250px) {
		.btn {
			padding: 5px 30px 5px 30px;
		}
	}

	/* START BUTTON */
	.btn-warning {
		background: var(--btnbg);
		color: var(--btnfontcolor);
		fill: #ffffff;
		border: none;
		text-decoration: none;
		outline: 0;
		/* box-shadow: -1px 6px 19px rgba(247, 129, 10, 0.25); */
		border-radius: 100px;
	}

	.btn-warning:hover {
		background: var(--btnbghover);
		color: var(--btnfontcolorhover);
		/* box-shadow: -1px 6px 13px rgba(255, 150, 43, 0.35); */
	}

	.btn-check:focus+.btn-warning,
	.btn-warning:focus {
		background: var(--btnbghover);
		color: var(--btnfontcolorhover);
		/* box-shadow: -1px 6px 13px rgba(255, 150, 43, 0.35); */
	}

	.btn-warning:active:focus {
		box-shadow: 0 0 0 0.25rem var(--btnactivefs);
	}

	.btn-warning:active {
		background: var(--btnbghover);
		color: var(--btnfontcolorhover);
		/* box-shadow: -1px 6px 13px rgba(255, 150, 43, 0.35); */
	}

	/* END BUTTON */

	.bg-success {
		font-size: 1rem;
		background-color: var(--btnbg) !important;
		color: var(--btnfontcolor) !important;
	}

	.bg-danger {
		font-size: 1rem;
	}


	.price-hp {
		font-size: 1rem;
		font-weight: 600;
		color: darkgray;
	}

	.amz-hp {
		font-size: .7rem;
		font-weight: 600;
		color: darkgray;
	}

	.fa-question-circle:before {
		/* content: "\f059"; */
		color: darkgray;
	}

	.fa-heart:before {
		color: crimson;
	}

	.fa-chevron-circle-right:before {
		color: darkgray;
	}
</style>


@section('content')
<div class="container mt-5 mb-5">
	<div class="d-flex justify-content-center row">
		@foreach ($products as $product)
		<div class="col-md-10">
			<div class="row p-2 bg-white border rounded">
				<div class="col-md-3 mt-1"><img class="img-thumbnail" src="https://www.delcourt.fr/img/cms/visuel2-article-classification-produits-entretien-delcourt-fr-min.jpg">
			</div>
				<div class="col-md-6 mt-1">
					<h5>{{ $product->title }}</h5>
					<div class="mt-1 mb-1 spec-1"><span>100% cotton</span><span class="dot"></span><span>Light weight</span><span class="dot"></span><span>Best finish<br></span></div>
					<p class="text-justify text-truncate para mb-0">{{ $product->description }}.<br><br></p>
				</div>
				<div class="align-items-center align-content-center col-md-3 border-left mt-1">
					<div class="d-flex flex-row align-items-center">
						<h4 class="mr-1">{{ $product->price }}</h4>
					</div>
					<h6 class="text-success">Free shipping</h6>
					<div class="d-flex flex-column mt-4"><button class="btn btn-outline-primary btn-sm mt-2" type="button">Add to wishlist</button></div>
				</div>
			</div>
		</div>
		@endforeach
	</div>
	{!! $products->links() !!}
</div>
<div class="row">
    @foreach($products as $product)
        <div class="col-xs-18 col-sm-6 col-md-3">
            <div class="thumbnail">
                <img src="{{ $product->image }}" alt="">
                <div class="caption">
                    <h4>{{ $product->name }}</h4>
                    <p>{{ $product->description }}</p>
                    <p><strong>Price: </strong> {{ $product->price }}$</p>
                    <!-- <p class="btn-holder"><a href="{{ route('add.to.cart', $product->id) }}" class="btn btn-warning btn-block text-center" role="button">Add to cart</a> </p> -->
                </div>
            </div>
        </div>
    @endforeach
</div>
@endsection
<!-- new -->

resources/views/layouts.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', '') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <img src="{{('/assets/img/soma.jpg') }}" class="img-fluid">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', '') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="{{ url('/') }}"> Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ route('aprop.index') }}">A props</a>
                        </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                        @if (Route::has('login'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @endif

                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                        @endif
                        @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                    <!-- card -->
                    <div class="row">
                        <div class="col-lg-12 col-sm-12 col-12 main-section">
                            <div class="dropdown">
                                <button type="button" class="btn btn-info" data-toggle="dropdown">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i> Cart <span class="badge badge-pill badge-danger">{{ count((array) session('cart')) }}</span>
                                </button>
                                <div class="dropdown-menu">
                                    <div class="row total-header-section">
                                        <div class="col-lg-6 col-sm-6 col-6">
                                            <i class="fa fa-shopping-cart" aria-hidden="true"></i> <span class="badge badge-pill badge-danger">{{ count((array) session('cart')) }}</span>
                                        </div>
                                        @php $total = 0 @endphp
                                        @foreach((array) session('cart') as $id => $details)
                                        @php $total += $details['price'] * $details['quantity'] @endphp
                                        @endforeach
                                        <div class="col-lg-6 col-sm-6 col-6 total-section text-right">
                                            <p>Total: <span class="text-info">$ {{ $total }}</span></p>
                                        </div>
                                    </div>
                                    @if(session('cart'))
                                    @foreach(session('cart') as $id => $details)
                                    <div class="row cart-detail">
                                        <div class="col-lg-4 col-sm-4 col-4 cart-detail-img">
                                            <img src="{{ $details['image'] }}" />
                                        </div>
                                        <div class="col-lg-8 col-sm-8 col-8 cart-detail-product">
                                            <p>{{ $details['name'] }}</p>
                                            <span class="price text-info"> ${{ $details['price'] }}</span> <span class="count"> Quantity:{{ $details['quantity'] }}</span>
                                        </div>
                                    </div>
                                    @endforeach
                                    @endif
                                    <div class="row">
                                        <div class="col-lg-12 col-sm-12 col-12 text-center checkout">
                                            <a href="{{ route('cart') }}" class="btn btn-primary btn-block">View all</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

</html>